### ISSUE TITLE
Callbacks are not called

### ISSUE THREAD

**Issue by vicltz** [machines-in-motion/mim_solvers#25]
It seems that callbacks are not called with mim-solver (CSQP in my case).

If I do 
``` py
solver.setCallbacks(
    [
            crocoddyl.CallbackVerbose(),
            crocoddyl.CallbackLogger(),
            crocoddyl.CallbackDisplay(display)
    ]
)
```

My callbacks are defined

```
In [5]: list(solver.getCallbacks())
Out[5]: 
[<crocoddyl.libcrocoddyl_pywrap.CallbackVerbose at 0x7fc0ee894040>,
 <crocoddyl.CallbackLogger at 0x7fc0ee894130>,
 <crocoddyl.CallbackDisplay at 0x7fc0ee894ef0>]
```

However, the logger doesn't work for instance with costs that is an empty list.

```
In [7]: log = solver.getCallbacks()[1]

In [8]: log.costs
Out[8]: []
```

CallbackDisplay is not called at each step as well.

I have this issue with the release, installed from `conda-forge`.

**Comment by ajordana** [comment]
Hello,

As of now, the callbacks can be called with `solver.with_callbacks = True`. We are currently working on adding more logs. I will close the issue but feel free to ask more questions.
