### ISSUE TITLE
Python binding failing compilation due to boost placeholder

### ISSUE THREAD

**Issue by Kotochleb** [machines-in-motion/mim_solvers#38]
When trying to compile code from source on release, `v0.0.5` I got errors like this:
```output
In file included from /usr/include/boost/python.hpp:28,
                 from /home/user/mim_solvers/include/mim_solvers/python.hpp:12,
                 from /home/user/mim_solvers/bindings/utils/callbacks.cpp:10:
/usr/include/boost/python/exception_translator.hpp: In function 'void boost::python::register_exception_translator(Translate, boost::type<Target>*)':
/usr/include/boost/python/exception_translator.hpp:22:83: error: '_1' was not declared in this scope
   22 |         boost::bind<bool>(detail::translate_exception<ExceptionType,Translate>(), _1, _2, translate)
```

After some digging into the problem, I found that commenting out the following preprocessor directive solves the problem.

https://github.com/machines-in-motion/mim_solvers/blob/5ee535f407d00d651df6f366c93ac339cc4e1dd5/bindings/utils/callbacks.cpp#L8

I did not find usage of it in Crocoddyl source code, which makes me confused about why it is here in the first place.
After making the change locally, I tested python binging with `solo12.py` example and it seemed to work.

The code was compiled on Ubuntu 22.04, bare OS, no Conda environment.

**Comment by skleff1994** [comment]
Thanks for pointing this out ! solved by #39
